### ISSUE TITLE
Saving vector representation as text or pickle

### ISSUE THREAD

**Issue by pleonard212** [YaleDHLab/tsne-images-webgl#2]
Question: the file extension of the vector representation is `.npz`:

https://github.com/YaleDHLab/tsne-images-webgl/blob/9fc627da78d09c11924a2654a5d2e5905faa96fa/utils/classify_images.py#L208

... but I think we may be saving as a generic text file:

https://github.com/YaleDHLab/tsne-images-webgl/blob/9fc627da78d09c11924a2654a5d2e5905faa96fa/utils/classify_images.py#L210

This only affects whether we `numpy.load` or `numpy.loadtxt` in later stages but just thought I'd check...

**Comment by duhaime** [comment]
Ah yes, we've been doing both. We should probably actually store zipped arrays to minimize disk usage...
